apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s-vol
    server: 192.168.70.10
  persistentVolumeReclaimPolicy: Retain
