apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejemplo-app
  template:
    metadata:
      labels:
        app: ejemplo-app
    spec:
      containers:
      - name: ejemplo-container
        image: nginx:latest
        volumeMounts:
        - mountPath: /mnt/data
          name: ejemplo-pvc
      volumes:
      - name: ejemplo-pvc
        persistentVolumeClaim:
          claimName: ejemplo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ejemplo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 1Gi
