apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-subdir-external-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
  template:
    metadata:
      labels:
        app: nfs-subdir-external-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-volume
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: <IP_DEL_SERVIDOR_NFS>
            - name: NFS_PATH
              value: /ruta/exportada
      volumes:
        - name: nfs-volume
          nfs:
            server: <IP_DEL_SERVIDOR_NFS>
            path: /ruta/exportada
