apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Ajusta el tamaño según lo necesites
  storageClassName: nfs-sc  # Usando el StorageClass configurado con el nfs-provisioner

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html  # Ruta donde NGINX sirve la web
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
