apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: nfs-sc  # Nombre de tu StorageClass (ver con `kubectl get storageclass`)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Tamaño simbólico para pruebas
