# deployment-webapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: php
        image: php:8.1-apache
        volumeMounts:
        - name: uploads
          mountPath: "/var/www/html/uploads"  # Directorio compartido para uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: nfs-shared-pvc
