# deployment-nfs.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deployment
spec:
  replicas: 2               # 2 pods idénticos
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
      labels:
        app: nginx-nfs
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nfs-shared
          mountPath: "/usr/share/nginx/html"  # Ambos pods montarán aquí el PVC
      volumes:
      - name: nfs-shared
        persistentVolumeClaim:
          claimName: nfs-shared-pvc  # Mismo PVC para ambos pods
