# pvc-shared.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-pvc
spec:
  storageClassName: nfs-sc  # Usa tu StorageClass NFS
  accessModes:
    - ReadWriteMany        # ¡Importante para múltiples pods!
  resources:
    requests:
      storage: 1Gi
