apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod-2
spec:
  containers:
    - name: nfs-test-container-2
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /mnt/nfs
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
