apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-provisioner-nfs-subdir-external-provisioner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-sc
