apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s-vol/app1
    server: 192.168.70.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s-vol/app2
    server: 192.168.70.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-3
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s-vol/app3
    server: 192.168.70.10
