apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: hello
spec:
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 10; done"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
